using System.Collections.Generic;
using System.IO;
using OoorFunc.Core;

namespace Ooor_cli
{
    /// <summary>
    /// Ooor-cli 多语言：读取 config/app.conf 的 language 字段（zh/en），
    /// 内嵌中英文翻译字典，提供 T(key) 与 Tf(key, args) 格式化方法。
    /// 不依赖外部 JSON 文件，自包含。
    /// </summary>
    internal static partial class CliLang
    {
       private static string _lang = "en";

        private static readonly Dictionary<string, string> Zh = new Dictionary<string, string>
        {
            { "unknownArg", "未知参数：{0}" },
            { "connectFail", "无法连接 llama-server（{0}）：{1}" },
            { "connectHint", "请先在 ooor 主界面点「启动服务」，或用 --base 指定服务地址后重试。" },
            { "pressAnyKey", "按任意键关闭窗口…" },
            { "sessionNotFound", "未找到会话记录（id={0}），将按新会话开始。" },
            { "sessionRestoreFail", "恢复会话失败：{0}" },
            { "agentNotFound", "未找到 Agent（{0}），使用内置默认人设。" },
            { "banner", "Ooor-cli {0}  命令行本地 AI 助手" },
            { "svcModel", "服务：{0}    模型：{1}" },
            { "agent", "Agent：{0}" },
            { "tools", "已注册工具（{0} 个）：{1}" },
            { "sessionLoaded", "已载入历史会话「{0}」· {1} 条消息，可直接接着聊。" },
            { "welcome", "输入问题开始对话；/help 查看命令；生成中 Ctrl+C 中断回答（不退出），输入时连按两次 Ctrl+C 退出。" },
            { "bye", "再见。" },
            { "thinking", "思考中" },
            { "maxSteps", "（已达到单轮最大步数 {0}，可继续追问或 /clear 重开会话）" },
            { "interrupted", "（已中断）" },
            { "error", "出错了：{0}" },
            { "svcStopped", "服务可能已停止，请在 ooor 主界面重新「启动服务」后重试。" },
            { "writtenFiles", "📝 本轮写入的文件（{0} 个）：" },
            { "executedFiles", "▶ 本轮执行/运行的文件（{0} 个）：" },
            { "newChat", "新对话 {0}" },
            { "saveFail", "（聊天记录保存失败：{0}）" },
            { "replayHeader", "────── 以下为历史会话回放（{0} 条消息）──────" },
            { "systemPrompt", "【系统提示词】" },
            { "replayEnd", "────── 历史回放结束，可直接继续提问 ──────" },
            { "reasonTime", "── 🧠 思考用时 {0}s · {1} 字符" },
            { "reasonRate", "── 🧠 思考用时 {0}s · {1} 字符 · {2} 字符/s (≈{3} tok/s 估算)" },
            { "contentTime", "── 📄 正文用时 {0}s · {1} 字符" },
            { "contentRate", "── 📄 正文用时 {0}s · {1} 字符 · {2} 字符/s (≈{3} tok/s 估算)" },
            { "chars", " 字符" },
            { "cleared", "已清空对话历史。" },
            { "toolsHeader", "已注册工具（{0} 个）：" },
            { "rootsHeader", "沙盒白名单目录：" },
            { "tempDir", "临时工作目录：{0}" },
            { "helpHeader", "命令（输入 / 会弹出菜单，↑/↓ 选择、回车确认）：" },
            { "helpAgent", "  /agent [名称]  选择 Agent 切换人设（不带名称则列出全部）" },
            { "helpNewConsole", "  /new-console   新开一个空白控制台窗口，沿用当前 Agent 与系统提示词" },
            { "helpTalk", "  /talk [序号]   切换到历史会话接着聊（不带序号则列出最近会话）" },
            { "helpFile", "  /file 路径     查看文件内容（也可在 / 菜单中选择后把路径插入输入）" },
            { "helpTools", "  /tools         查看已注册的 AI 工具" },
            { "helpRoots", "  /roots         查看沙盒白名单目录" },
            { "helpHelp", "  /help          显示本帮助" },
            { "helpClear", "  /clear         清空对话历史（重新开始）" },
            { "helpExit", "  /exit          退出（输入时连按两次 Ctrl+C 同样退出；生成中 Ctrl+C 只中断回答）" },
            { "helpArgs", "启动参数：--base URL / --root DIR（可多次）/ --trust / --agent 名称 / --session ID" },
            { "unknownCmd", "未知命令：{0}（/help 查看可用命令）" },
            { "noAgent", "还没有 Agent。请在 OOOR 主程序的「Agent 管理」中新建。" },
            { "agentList", "可用 Agent（用 /agent 名称 切换）：" },
            { "agentNotFound2", "找不到 Agent：{0}" },
            { "agentSwitched", "已切换到 Agent：{0}" },
            { "defaultModel", "默认模型：{0}（实际以服务当前加载的模型为准）" },
            { "newConsoleOk", "已新开空白控制台窗口{0}，当前窗口不受影响。" },
            { "newConsoleBuiltin", "（内置默认人设）" },
            { "newConsoleAgent", "（Agent：{0}）" },
            { "newConsoleFail", "新建控制台窗口失败：{0}" },
            { "noHistory", "还没有历史聊天记录。" },
            { "talkList", "最近的会话（用 /talk 序号 切换）：" },
            { "unnamed", "(未命名)" },
            { "autoModel", "(自动)" },
            { "sessionNotFound2", "找不到会话：{0}" },
            { "curSaveFail", "（当前会话保存失败：{0}）" },
            { "fileUsage", "用法：/file 文件路径（在 / 菜单中选择文件会直接把路径插入输入行）。" },
            { "fileNotExist", "文件不存在：{0}" },
            { "fileReadFail", "读取失败：{0}" },
            { "fileTruncated", "…（共 {0} 字符，已截断）" },
            { "usageTitle", "用法: Ooor-cli [--base URL] [--root DIR] ... [--trust]" },
            { "usageBase", "  --base URL      llama-server 地址（默认读取 ooor 的 run_state.conf，再退回 http://127.0.0.1:6080）" },
            { "usageRoot", "  --root DIR      额外沙盒白名单目录（可多次指定）" },
            { "usageTrust", "  --trust         允许模型自行判断跳过高危确认（默认一律 Y/N 确认）" },
            { "usageWeb", "  --web           打开 WebView2 高仿控制台窗口（黑底网页终端），不进原生控制台（可加 --devtools 调试页面）" },
            { "usageSession", "  --session ID    从聊天记录库恢复指定会话，载入历史消息接着聊" },
            { "usageAgent", "  --agent NAME    以指定 Agent 的系统提示词开始一个空白新对话（/new-console 用）" },
            { "usageModel", "  --model PATH    期望模型（实际以服务当前加载的模型为准，仅用于记录）" },
            { "usageHelp", "  --help          显示本帮助" },
            { "usageRepl", "进入程序后为交互式 REPL，输入 /help 查看会话命令。" },
            { "confirmTitle", "需要确认" },
            { "confirmPrompt", "  是否继续? [Y/N] (Enter=N): " },
            { "truncatedLines", "…（共 {0} 行，已截断）" },
            { "toolFail", "⚙(失败) " },
            { "cmd.agent", "选择 Agent" },
            { "cmd.newConsole", "新建同 Agent 的空白窗口" },
            { "cmd.talk", "切换历史会话接着聊" },
            { "cmd.file", "插入文件" },
            { "cmd.help", "帮助" },
            { "cmd.clear", "清空对话" },
            { "cmd.exit", "退出" },
            { "doubleCtrlC", "再按一次 Ctrl+C 退出窗口；按其他任意键继续输入。" },
            { "sys.confirmTrust", "当前为「开放权限」模式：写文件/删文件/执行命令不需要用户确认，直接执行。即便不再询问，仍应先用一句话说明你打算做什么，首次涉及用户既有文件时尤其要说清楚。" },
            { "sys.confirmNormal", "写文件/删文件/执行命令属于高危操作：每次都会在终端请求用户输入 Y/N 确认，被拒绝时不要原样重试，应说明原因或换方案。" },
            { "sys.prompt", "你是运行在用户 Windows 电脑终端里的本地 AI 助手 Ooor-cli，可以调用工具真实地查看与操作文件。不要声称自己无法访问文件系统：需要信息时直接调用对应工具（list_roots / list_directory / read_file / get_app_info 等）。只能访问沙盒白名单目录（默认含当前目录），越权会被拒绝；开始文件操作前先调 list_roots。给文件的 path 参数若只写文件名或相对路径，会自动落到临时工作目录，工具返回值里会给出实际完整路径，请以返回的路径为准。{0}已开启联网工具（web_search / fetch_url），可以联网获取实时信息。回答用简体中文、Markdown 排版，简洁直接，代码放进代码块。" },
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "unknownArg", "Unknown argument: {0}" },
            { "connectFail", "Cannot connect to llama-server ({0}): {1}" },
            { "connectHint", "Please click \"Start Service\" in the ooor main window first, or use --base to specify the service address." },
            { "pressAnyKey", "Press any key to close…" },
            { "sessionNotFound", "Session not found (id={0}), starting a new session." },
            { "sessionRestoreFail", "Failed to restore session: {0}" },
            { "agentNotFound", "Agent not found ({0}), using built-in default persona." },
            { "banner", "Ooor-cli {0}  CLI Local AI Assistant" },
            { "svcModel", "Service: {0}    Model: {1}" },
            { "agent", "Agent: {0}" },
            { "tools", "Registered tools ({0}): {1}" },
            { "sessionLoaded", "Loaded history session \"{0}\" · {1} messages, continue chatting." },
            { "welcome", "Type a question to start; /help for commands; Ctrl+C during generation interrupts (no exit); double Ctrl+C while typing exits." },
            { "bye", "Goodbye." },
            { "thinking", "Thinking" },
            { "maxSteps", "(Reached max steps per turn {0}, continue asking or /clear to restart session)" },
            { "interrupted", "(Interrupted)" },
            { "error", "Error: {0}" },
            { "svcStopped", "Service may have stopped, please click \"Start Service\" again in the ooor main window." },
            { "writtenFiles", "📝 Files written this turn ({0}):" },
            { "executedFiles", "▶ Files executed/run this turn ({0}):" },
            { "newChat", "New chat {0}" },
            { "saveFail", "(Chat history save failed: {0})" },
            { "replayHeader", "────── History replay ({0} messages) ──────" },
            { "systemPrompt", "[System Prompt]" },
            { "replayEnd", "────── Replay ended, continue asking ──────" },
            { "reasonTime", "── 🧠 Reasoning {0}s · {1} chars" },
            { "reasonRate", "── 🧠 Reasoning {0}s · {1} chars · {2} chars/s (≈{3} tok/s est.)" },
            { "contentTime", "── 📄 Content {0}s · {1} chars" },
            { "contentRate", "── 📄 Content {0}s · {1} chars · {2} chars/s (≈{3} tok/s est.)" },
            { "chars", " chars" },
            { "cleared", "Chat history cleared." },
            { "toolsHeader", "Registered tools ({0}):" },
            { "rootsHeader", "Sandbox whitelist directories:" },
            { "tempDir", "Temp working directory: {0}" },
            { "helpHeader", "Commands (type / for menu, ↑/↓ to select, Enter to confirm):" },
            { "helpAgent", "  /agent [name]    Switch Agent persona (no name to list all)" },
            { "helpNewConsole", "  /new-console     Open a new blank console window, keeps current Agent & system prompt" },
            { "helpTalk", "  /talk [index]    Switch to a history session (no index to list recent)" },
            { "helpFile", "  /file PATH       View file content (or pick from / menu to insert path)" },
            { "helpTools", "  /tools           List registered AI tools" },
            { "helpRoots", "  /roots           List sandbox whitelist directories" },
            { "helpHelp", "  /help            Show this help" },
            { "helpClear", "  /clear           Clear chat history (restart)" },
            { "helpExit", "  /exit            Exit (double Ctrl+C while typing also exits; Ctrl+C during gen only interrupts)" },
            { "helpArgs", "Args: --base URL / --root DIR (repeatable) / --trust / --agent NAME / --session ID" },
            { "unknownCmd", "Unknown command: {0} (/help for available commands)" },
            { "noAgent", "No Agent yet. Create one in the OOOR main program's \"Agent Manager\"." },
            { "agentList", "Available Agents (use /agent NAME to switch):" },
            { "agentNotFound2", "Agent not found: {0}" },
            { "agentSwitched", "Switched to Agent: {0}" },
            { "defaultModel", "Default model: {0} (actual = currently loaded service model)" },
            { "newConsoleOk", "Opened a new blank console window{0}, current window unaffected." },
            { "newConsoleBuiltin", " (built-in persona)" },
            { "newConsoleAgent", " (Agent: {0})" },
            { "newConsoleFail", "Failed to open new console window: {0}" },
            { "noHistory", "No chat history yet." },
            { "talkList", "Recent sessions (use /talk INDEX to switch):" },
            { "unnamed", "(untitled)" },
            { "autoModel", "(auto)" },
            { "sessionNotFound2", "Session not found: {0}" },
            { "curSaveFail", "(Current session save failed: {0})" },
            { "fileUsage", "Usage: /file PATH (pick a file from / menu to insert path directly)." },
            { "fileNotExist", "File not found: {0}" },
            { "fileReadFail", "Read failed: {0}" },
            { "fileTruncated", "…({0} chars total, truncated)" },
            { "usageTitle", "Usage: Ooor-cli [--base URL] [--root DIR] ... [--trust]" },
            { "usageBase", "  --base URL      llama-server address (default: read ooor run_state.conf, fallback http://127.0.0.1:6080)" },
            { "usageRoot", "  --root DIR      Extra sandbox whitelist dir (repeatable)" },
            { "usageTrust", "  --trust         Let AI skip high-risk confirmations (default: always Y/N confirm)" },
            { "usageWeb", "  --web           Open the WebView2 console-style window (black web terminal) instead of the native console (add --devtools to debug the page)" },
            { "usageSession", "  --session ID    Restore a session from chat history DB, load messages to continue" },
            { "usageAgent", "  --agent NAME    Start a blank new chat with specified Agent's system prompt (used by /new-console)" },
            { "usageModel", "  --model PATH    Expected model (actual = service loaded model, for record only)" },
            { "usageHelp", "  --help          Show this help" },
            { "usageRepl", "Interactive REPL after launch, type /help for session commands." },
            { "confirmTitle", "Confirmation needed" },
            { "confirmPrompt", "  Continue? [Y/N] (Enter=N): " },
            { "truncatedLines", "…({0} lines total, truncated)" },
            { "toolFail", "⚙(fail) " },
            { "cmd.agent", "Select Agent" },
            { "cmd.newConsole", "New blank window with same Agent" },
            { "cmd.talk", "Switch to history session" },
            { "cmd.file", "Insert file" },
            { "cmd.help", "Help" },
            { "cmd.clear", "Clear chat" },
            { "cmd.exit", "Exit" },
            { "doubleCtrlC", "Press Ctrl+C again to exit; press any other key to continue." },
            { "sys.confirmTrust", "You are in \"open permission\" mode: writing/deleting files or executing commands does NOT require user confirmation—execute directly. Even without confirmation, always briefly state what you intend to do first, especially when touching existing user files." },
            { "sys.confirmNormal", "Writing/deleting files or executing commands are high-risk operations: each one prompts the user for Y/N confirmation in the terminal. If rejected, do NOT retry the same action—explain why or propose an alternative." },
            { "sys.prompt", "You are Ooor-cli, a local AI assistant running in the user's Windows terminal. You can call tools to actually view and manipulate files. Do NOT claim you cannot access the filesystem: when you need information, call the relevant tool directly (list_roots / list_directory / read_file / get_app_info, etc.). You may only access sandbox whitelist directories (current directory included by default); out-of-bounds access will be denied. Call list_roots before any file operation. If a file's path argument is just a filename or relative path, it will be resolved to the temp working directory; the tool returns the actual full path—use that returned path. {0}Internet tools are enabled (web_search / fetch_url), so you can fetch real-time information online. Respond in English with Markdown formatting; be concise and direct; put code in code blocks." },
        };
    }
    
}